apiVersion: apps/v1
kind: Deployment
metadata:
  name: validate-frontend
spec:
  template:
    spec:
      containers:
        - name: validate-frontend
          env:
            # Production API URL - confirmed working
            - name: BACKEND_API_URL
              value: "https://pipeline-api.klimatkollen.se"
